## Intro to Numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(3,)

In [7]:
arr.dtype

dtype('int32')

In [9]:
arr1=np.ones((2,2,2))

In [10]:
arr

array([1, 2, 3])

In [11]:
arr1

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
arr2=np.zeros((3,3,3))

In [14]:
arr2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
arr1

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [21]:
import pandas as pd

In [24]:
df=pd.DataFrame(arr)

In [25]:
df

0
0  1
1  2
2  3

In [39]:
arn=np.random.randint(0,10,((3,2,3,4)))

In [40]:
arn

array([[[[2, 0, 4, 8],
         [7, 1, 4, 9],
         [3, 6, 7, 1]],

        [[0, 2, 7, 0],
         [0, 9, 8, 2],
         [0, 5, 5, 0]]],


       [[[9, 0, 8, 4],
         [5, 1, 4, 0],
         [7, 2, 0, 3]],

        [[9, 8, 3, 7],
         [1, 0, 1, 4],
         [6, 1, 0, 1]]],


       [[[0, 1, 8, 4],
         [1, 6, 8, 5],
         [2, 4, 7, 4]],

        [[1, 2, 8, 5],
         [2, 9, 6, 2],
         [5, 7, 7, 5]]]])

In [31]:
np.random.seed(7)
r3 = np.random.random((6,3))
r3

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396]])

In [32]:
arn=np.random.randint(0,10,((3,2,4,4)))

In [33]:
arr

array([1, 2, 3])

In [34]:
arn

array([[[[8, 7, 5, 0],
         [0, 2, 8, 9],
         [6, 4, 9, 7],
         [3, 3, 8, 3]],

        [[0, 1, 0, 0],
         [6, 7, 7, 9],
         [3, 0, 7, 7],
         [7, 0, 5, 4]]],


       [[[3, 1, 3, 1],
         [3, 4, 3, 1],
         [9, 5, 9, 1],
         [2, 3, 2, 2]],

        [[5, 7, 3, 0],
         [9, 9, 3, 4],
         [5, 3, 0, 4],
         [8, 6, 7, 2]]],


       [[[7, 3, 8, 6],
         [6, 5, 6, 5],
         [7, 1, 5, 4],
         [4, 9, 9, 0]],

        [[6, 2, 6, 8],
         [2, 4, 1, 6],
         [1, 5, 1, 6],
         [9, 8, 6, 5]]]])