In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])

In [3]:
arr1

array([1, 2, 3])

In [12]:
arr2=np.ones((4,5,6))

In [15]:
arr2[1]

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr2.ndim

3

In [20]:
ar3 = np.random.randint(10, size=(2,2, 3))

In [21]:
ar3

array([[[4, 5, 9],
        [3, 5, 5]],

       [[9, 1, 4],
        [1, 6, 8]]])

In [19]:
ar3.ndim

3