# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape,arr1.dtype,arr1.size

((3,), dtype('int32'), 3)

In [7]:
# Attributes of 2-dimensional array
arr2.shape,arr2.dtype,arr2.size

((2, 3), dtype('int32'), 6)

In [9]:
# Attributes of 3-dimensional array
arr3.shape,arr3.dtype,arr3.size,arr3.ndim

((3, 1, 3), dtype('int32'), 9, 3)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
arones=np.ones((10,2))
arones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:

# Create an array of shape (7, 2, 3) of only zeros
ar0=np.zeros((7,2,3))
ar0

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3


In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randarr=np.random.randint(10,size=(7,2))
randarr

array([[8, 8],
       [8, 3],
       [7, 9],
       [7, 0],
       [0, 3],
       [9, 4],
       [6, 7]])

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))

array([[0.18830244, 0.30706805, 0.31759824, 0.45294442, 0.25357898],
       [0.0178124 , 0.86143429, 0.61238517, 0.59149919, 0.89898414],
       [0.2408371 , 0.2144224 , 0.27116955, 0.77741696, 0.91844171]])

In [26]:
# Set the random seed to 42
np.random.seed(42)
np.random.randint(10,size=(4,6))

# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(5)
arr=np.random.randint(10,size=(3,7))
arr
# Find the unique numbers in the array you just created


array([[3, 6, 6, 0, 9, 8, 4],
       [7, 0, 0, 7, 1, 5, 7],
       [0, 1, 4, 6, 2, 9, 9]])

In [36]:
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Get the first 2 rows of latest array you created
arr[:2]

array([[3, 6, 6, 0, 9, 8, 4],
       [7, 0, 0, 7, 1, 5, 7]])

In [39]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2,:2]

array([[3, 6],
       [7, 0]])

In [74]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1=np.ones((3, 5))
arr2=np.ones((3, 5))

In [75]:
# Add the two arrays together
ar5=arr1+arr2
ar5

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [44]:
# Create another array of ones of shape (5, 3)
arr3=np.random.random((5,3))
arr3

array([[0.52367529, 0.492136  , 0.7318711 ],
       [0.01458075, 0.09336303, 0.82655425],
       [0.83349274, 0.89241102, 0.9580135 ],
       [0.56133712, 0.0905487 , 0.99598891],
       [0.47740172, 0.68491561, 0.84337526]])

In [76]:
# Try add the array of ones and the other most recent array together
arr3+ar5.T

array([[2.52367529, 2.492136  , 2.7318711 ],
       [2.01458075, 2.09336303, 2.82655425],
       [2.83349274, 2.89241102, 2.9580135 ],
       [2.56133712, 2.0905487 , 2.99598891],
       [2.47740172, 2.68491561, 2.84337526]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [78]:
# Create another array of ones of shape (3, 5)
ar=np.ones((3,5))

In [81]:
# Subtract the new array of ones from the other most recent array
ar1=ar-arr3.T

In [82]:
# Multiply the ones array with the latest array
ar1*2

array([[0.95264942, 1.9708385 , 0.33301452, 0.87732576, 1.04519656],
       [1.015728  , 1.81327393, 0.21517797, 1.81890261, 0.63016879],
       [0.5362578 , 0.3468915 , 0.08397299, 0.00802217, 0.31324947]])

In [83]:
# Take the latest array to the power of 2 using '**'
ar1**2

array([[2.26885230e-01, 9.71051096e-01, 2.77246669e-02, 1.92425122e-01,
        2.73108962e-01],
       [2.57925844e-01, 8.21990589e-01, 1.15753892e-02, 8.27101675e-01,
        9.92781744e-02],
       [7.18931069e-02, 3.00834286e-02, 1.76286581e-03, 1.60888184e-05,
        2.45313079e-02]])

In [84]:
# Do the same thing with np.square()np.
np.square(ar1)

array([[2.26885230e-01, 9.71051096e-01, 2.77246669e-02, 1.92425122e-01,
        2.73108962e-01],
       [2.57925844e-01, 8.21990589e-01, 1.15753892e-02, 8.27101675e-01,
        9.92781744e-02],
       [7.18931069e-02, 3.00834286e-02, 1.76286581e-03, 1.60888184e-05,
        2.45313079e-02]])

In [85]:
# Find the mean of the latest array using np.mean()
np.mean(ar1)

0.3986889995922678

In [86]:
# Find the maximum of the latest array using np.max()
np.max(ar1)

0.985419248903648

In [87]:
# Find the minimum of the latest array using np.min()
np.min(ar1)

0.004011086938481401

In [88]:
# Find the standard deviation of the latest array
np.std(ar1)

0.311240504064851

In [89]:
# Find the variance of the latest array
np.var(ar1)

0.09687065137054253

In [93]:
# Reshape the latest array to (3, 5, 1)
ar1=ar1.reshape(3,5,1)
ar1

array([[[0.47632471],
        [0.98541925],
        [0.16650726],
        [0.43866288],
        [0.52259828]],

       [[0.507864  ],
        [0.90663697],
        [0.10758898],
        [0.9094513 ],
        [0.31508439]],

       [[0.2681289 ],
        [0.17344575],
        [0.0419865 ],
        [0.00401109],
        [0.15662474]]])

In [94]:
# Transpose the latest array
ar1.T

array([[[0.47632471, 0.507864  , 0.2681289 ],
        [0.98541925, 0.90663697, 0.17344575],
        [0.16650726, 0.10758898, 0.0419865 ],
        [0.43866288, 0.9094513 , 0.00401109],
        [0.52259828, 0.31508439, 0.15662474]]])

What does the transpose do?

In [96]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1=np.random.random((3,3))
arr2=np.random.random((3,2))

In [100]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

array([[0.60056833, 0.60056833, 0.60056833, 0.60056833, 0.60056833],
       [1.32761422, 1.32761422, 1.32761422, 1.32761422, 1.32761422],
       [2.01450825, 2.01450825, 2.01450825, 2.01450825, 2.01450825]])

In [102]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1=np.random.random((4, 3))
arr2=np.random.random((4, 3))

In [104]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2.T)

array([[1.16734265, 1.19965117, 2.00771176, 1.07650704],
       [0.60993793, 0.89476547, 1.39614571, 0.83030347],
       [0.57503238, 0.41939068, 0.75953627, 0.25933556],
       [0.45347354, 0.40608332, 0.69060305, 0.19734923]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [106]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1=np.random.random((3,3))
arr2=np.random.random((3,3))
arr1,arr2

(array([[0.84998003, 0.51473797, 0.44660783],
        [0.80047642, 0.02039138, 0.57261865],
        [0.41138362, 0.9851368 , 0.80140153]]),
 array([[0.0539621 , 0.19047777, 0.45241885],
        [0.70294208, 0.33204815, 0.3599832 ],
        [0.92147057, 0.95363051, 0.40768573]]))

In [107]:
# Compare the two arrays with '>'
arr1>arr2

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [108]:
# Compare the two arrays with '>='
arr1>=arr2

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [109]:
# Find which elements of the first array are greater than 7
arr1>7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [110]:
# Which parts of each array are equal? (try using '==')
arr1==arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [111]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[0.44660783, 0.51473797, 0.84998003],
       [0.02039138, 0.57261865, 0.80047642],
       [0.41138362, 0.80140153, 0.9851368 ]])

In [112]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)

array([[2, 1, 0],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.